In [1]:
import numpy as np
import pandas as pd

In [3]:
delivery=pd.read_csv("deliveries.csv")
delivery

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [5]:
match=pd.read_csv('matches.csv')
match

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [7]:
#we use merge function when we have to need merge two data set
#like here we want only orange cap player of evry season which is not possible using only one dataset that's why need to merge this dataset
#we are giving the column name on which we are going to merge dataset 
new_match=delivery.merge(match,left_on='match_id',right_on='id') #this is inner merge mean only when column is matched only that row is picked otherwise it will dropped

In [8]:
new_match #it has all row mean no data loss here #but column in increased

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [11]:
#now we  have to make goup on the basis of season and player bcs we need highest run's player of each season so, first we have to find player wise each season
x=new_match.groupby(['season','batsman']) #heer we have two index column first is season and second is batsman

In [26]:
#now we will add the run of each of of each player
#we want only seaon and batsman who has orage cap in the season
#it also return an dataframe ,lets use it with sum of some column of dataframe on the basis of player in a season
x.sum()

                          match_id  inning  \
season batsman
2008   A Chopra               5182      58
       A Kumble               1597      25
       A Mishra               4080      79
       A Mukund                110       2
       A Nehra                 930      26
...                            ...     ...
2017   Washington Sundar       517      19
       YK Pathan              3182     196
       YS Chahal               620      50
       Yuvraj Singh           5747     262
       Z Khan                  544      26

                                                               batting_team  \
season batsman
2008   A Chopra           Kolkata Knight RidersKolkata Knight RidersKolk...
       A Kumble           Royal Challengers BangaloreRoyal Challengers B...
       A Mishra           Delhi DaredevilsDelhi DaredevilsDelhi Daredevi...
       A Mukund                                         Chennai Super Kings
       A Nehra            Mumbai IndiansMumbai IndiansMumbai IndiansMumb...
...                                                                     ...
2017   Washington Sundar  Rising Pune SupergiantRising Pune SupergiantRi...
       YK Pathan          Kolkata Knight RidersKolkata Knight RidersKolk...
       YS Chahal          Royal Challengers BangaloreRoyal Challengers B...
       Yuvraj Singh       Sunrisers HyderabadSunrisers HyderabadSunriser...
       Z Khan             Delhi DaredevilsDelhi DaredevilsDelhi Daredevi...

                                                               bowling_team  \
season batsman
2008   A Chopra           Royal Challengers BangaloreRoyal Challengers B...
       A Kumble           Kings XI PunjabKings XI PunjabKings XI PunjabK...
       A Mishra           Rajasthan RoyalsRajasthan RoyalsRajasthan Roya...
       A Mukund                                            Rajasthan Royals
       A Nehra            Chennai Super KingsChennai Super KingsKings XI...
...                                                                     ...
2017   Washington Sundar  Mumbai IndiansMumbai IndiansKolkata Knight Rid...
       YK Pathan          Mumbai IndiansMumbai IndiansMumbai IndiansMumb...
       YS Chahal          Sunrisers HyderabadSunrisers HyderabadSunriser...
       Yuvraj Singh       Royal Challengers BangaloreRoyal Challengers B...
       Z Khan             Royal Challengers BangaloreMumbai IndiansMumba...

                          over  ball  \
season batsman
2008   A Chopra            301   202
       A Kumble            309    66
       A Mishra            565   132
       A Mukund             20     7
       A Nehra             253    54
...                        ...   ...
2017   Washington Sundar   235    53
       YK Pathan          1453   470
       YS Chahal           482    96
       Yuvraj Singh       2669   699
       Z Khan              184    48

                                                                non_striker  \
season batsman
2008   A Chopra           BJ HodgeBJ HodgeBJ HodgeBJ HodgeBJ HodgeSC Gan...
       A Kumble           R DravidR DravidR DravidR DravidR DravidDW Ste...
       A Mishra           TM DilshanTM DilshanTM DilshanTM DilshanTM Dil...
       A Mukund                                                     MS Gony
       A Nehra            AM NayarAM NayarDS KulkarniDS KulkarniDS Kulka...
...                                                                     ...
2017   Washington Sundar  DT ChristianDT ChristianDT ChristianDT Christi...
       YK Pathan          MK PandeyMK PandeyMK PandeyMK PandeyMK PandeyM...
       YS Chahal          TS MillsTS MillsTS MillsTS MillsA ChoudharyA C...
       Yuvraj Singh       MC HenriquesMC HenriquesMC HenriquesMC Henriqu...
       Z Khan             A MishraA MishraA MishraA MishraA MishraA Mish...

                                                                     bowler  \
season batsman
2008   A Chopra           DW SteynDW SteynDW SteynZ KhanDW SteynDP Vijay...
       A Kumble           PP ChawlaPP ChawlaPP ChawlaPP ChawlaVRV SinghV...
       A Mishra           MM PatelSK TrivediSK TrivediSK TrivediSK Trive...
       A Mukund                                               Sohail Tanvir
       A Nehra            Joginder SharmaJoginder SharmaS SreesanthS Sre...
...                                                                     ...
2017   Washington Sundar  JJ BumrahJJ BumrahCR WoakesCR WoakesC de Grand...
       YK Pathan          JJ BumrahJJ BumrahJJ BumrahHarbhajan SinghHarb...
       YS Chahal          A NehraA NehraB KumarB KumarB KumarBCJ Cutting...
       Yuvraj Singh       STR BinnySTR BinnyS AravindS AravindS AravindS...
       Z Khan             P NegiHarbhajan SinghKV SharmaHH PandyaHH Pand...

                          is_super_over  wide_runs  ...  \
season batsman                                      ...
2008   A Chopra                       0          3  ...
       A Kumble                       0          0  ...
       A Mishra                       0          0  ...
       A Mukund                       0          0  ...
       A Nehra                        0          0  ...
...                                 ...        ...  ...
2017   Washington Sundar              0          0  ...
       YK Pathan                      0         11  ...
       YS Chahal                      0          0  ...
       Yuvraj Singh                   0         11  ...
       Z Khan                         0          0  ...

                                                                     result  \
season batsman
2008   A Chopra           normalnormalnormalnormalnormalnormalnormalnorm...
       A Kumble           normalnormalnormalnormalnormalnormalnormalnorm...
       A Mishra           normalnormalnormalnormalnormalnormalnormalnorm...
       A Mukund                                                      normal
       A Nehra            normalnormalnormalnormalnormalnormalnormalnorm...
...                                                                     ...
2017   Washington Sundar  normalnormalnormalnormalnormalnormalnormalnorm...
       YK Pathan          normalnormalnormalnormalnormalnormalnormalnorm...
       YS Chahal          normalnormalnormalnormalnormalnormalnormalnorm...
       Yuvraj Singh       normalnormalnormalnormalnormalnormalnormalnorm...
       Z Khan             normalnormalnormalnormalnormalnormalnormalnorm...

                          dl_applied  \
season batsman
2008   A Chopra                    0
       A Kumble                    0
       A Mishra                    0
       A Mukund                    0
       A Nehra                     0
...                              ...
2017   Washington Sundar           0
       YK Pathan                   1
       YS Chahal                   0
       Yuvraj Singh                9
       Z Khan                      0

                                                                     winner  \
season batsman
2008   A Chopra           Kolkata Knight RidersKolkata Knight RidersKolk...
       A Kumble           Kings XI PunjabKings XI PunjabKings XI PunjabK...
       A Mishra           Rajasthan RoyalsRajasthan RoyalsRajasthan Roya...
       A Mukund                                            Rajasthan Royals
       A Nehra            Chennai Super KingsChennai Super KingsKings XI...
...                                                                     ...
2017   Washington Sundar  Rising Pune SupergiantRising Pune SupergiantRi...
       YK Pathan          Mumbai IndiansMumbai IndiansMumbai IndiansMumb...
       YS Chahal          Sunrisers HyderabadSunrisers HyderabadSunriser...
       Yuvraj Singh       Sunrisers HyderabadSunrisers HyderabadSunriser...
       Z Khan             Royal Challengers BangaloreMumbai IndiansMumba...

                          win_by_runs  win_by_wickets  \
season batsman
2008   A Chopra                  1014              41
       A Kumble                   534              51
       A Mishra                  1261              15
       A Mukund                    10               0
       A Nehra                    673               0
...                               ...             ...
2017   Washington Sundar           64              12
       YK Pathan                 1822             299
       YS Chahal                 1088              14
       Yuvraj Singh              2597             437
       Z Khan                    1631               0

                                                            player_of_match  \
season batsman
2008   A Chopra           SC GangulySC GangulySC GangulySC GangulySC Gan...
       A Kumble           S SreesanthS SreesanthS SreesanthS SreesanthS ...
       A Mishra           SR WatsonSR WatsonSR WatsonSR WatsonSR WatsonS...
       A Mukund                                                   JA Morkel
       A Nehra            ML HaydenML HaydenKC SangakkaraKC SangakkaraKC...
...                                                                     ...
2017   Washington Sundar  BA StokesBA StokesRA TripathiRA TripathiRA Tri...
       YK Pathan          N RanaN RanaN RanaN RanaN RanaN RanaN RanaN Ra...
       YS Chahal          Yuvraj SinghYuvraj SinghYuvraj SinghYuvraj Sin...
       Yuvraj Singh       Yuvraj SinghYuvraj SinghYuvraj SinghYuvraj Sin...
       Z Khan             KM JadhavLMP SimmonsLMP SimmonsLMP SimmonsLMP ...

                                                                      venue  \
season batsman
2008   A Chopra           Eden GardensEden GardensEden GardensEden Garde...
       A Kumble           M Chinnaswamy StadiumM Chinnaswamy StadiumM Ch...
       A Mishra           Sawai Mansingh StadiumSawai Mansingh StadiumSa...
       A Mukund                             MA Chidambaram Stadium, Chepauk
       A Nehra            MA Chidambaram Stadium, ChepaukMA Chidambaram ...
...                                                                     ...
2017   Washington Sundar  Wankhede StadiumWankhede StadiumEden GardensEd...
       YK Pathan          Wankhede StadiumWankhede StadiumWankhede Stadi...
       YS Chahal          Rajiv Gandhi International Stadium, UppalRajiv...
       Yuvraj Singh       Rajiv Gandhi International Stadium, UppalRajiv...
       Z Khan             M Chinnaswamy StadiumFeroz Shah KotlaFeroz Sha...

                                                                    umpire1  \
season batsman
2008   A Chopra           Asad RaufAsad RaufAsad RaufAsad RaufAsad RaufI...
       A Kumble           SJ DavisSJ DavisSJ DavisSJ DavisSJ DavisSJ Dav...
       A Mishra           SJ DavisSJ DavisSJ DavisSJ DavisSJ DavisAsad R...
       A Mukund                                                   DJ Harper
       A Nehra            DJ HarperDJ HarperAleem DarAleem DarAleem DarA...
...                                                                     ...
2017   Washington Sundar  A Nand KishoreA Nand KishoreKN Ananthapadmanab...
       YK Pathan          Nitin MenonNitin MenonNitin MenonNitin MenonNi...
       YS Chahal          AY DandekarAY DandekarAY DandekarAY DandekarAY...
       Yuvraj Singh       AY DandekarAY DandekarAY DandekarAY DandekarAY...
       Z Khan             Nitin MenonNitin MenonNitin MenonNitin MenonNi...

                                                                    umpire2  \
season batsman
2008   A Chopra           IL HowellIL HowellIL HowellIL HowellIL HowellA...
       A Kumble           BR DoctroveBR DoctroveBR DoctroveBR DoctroveBR...
       A Mishra           RE KoertzenRE KoertzenRE KoertzenRE KoertzenRE...
       A Mukund                                                  SL Shastri
       A Nehra            GA PratapkumarGA PratapkumarAM SahebaAM Saheba...
...                                                                     ...
2017   Washington Sundar  S RaviS RaviA Nand KishoreA Nand KishoreA Nand...
       YK Pathan          CK NandanCK NandanCK NandanCK NandanCK NandanC...
       YS Chahal          NJ LlongNJ LlongNJ LlongNJ LlongNJ LlongNJ Llo...
       Yuvraj Singh       NJ LlongNJ LlongNJ LlongNJ LlongNJ LlongNJ Llo...
       Z Khan             CK NandanCK NandanCK NandanCK NandanCK NandanC...

                         umpire3
season batsman
2008   A Chopra              0.0
       A Kumble              0.0
       A Mishra              0.0
       A Mukund              0.0
       A Nehra               0.0
...                          ...
2017   Washington Sundar     0.0
       YK Pathan             0.0
       YS Chahal             0.0
       Yuvraj Singh          0.0
       Z Khan                0.0

[1531 rows x 37 columns]

In [32]:
#now we add runs of each column and it will return a series bcs we are fetching column batsman_runs
#we also sort it ont the basis of batsman_run so that we can see who is on the top in each season 
x.sum()['batsman_runs'].sort_values(ascending=False)

season  batsman
2016    V Kohli        973
        DA Warner      848
2013    MEK Hussey     733
2012    CH Gayle       733
2013    CH Gayle       720
                      ...
2017    MM Patel         0
2012    AC Blizzard      0
2011    AB Dinda         0
2017    AD Nath          0
2008    L Balaji         0
Name: batsman_runs, Length: 1531, dtype: int64

In [34]:
#now we will convert it into dataframe to do that we use a funtion called reset_index()
y=x.sum()['batsman_runs'].sort_values(ascending=False).reset_index()
y

      season      batsman  batsman_runs
0       2016      V Kohli           973
1       2016    DA Warner           848
2       2013   MEK Hussey           733
3       2012     CH Gayle           733
4       2013     CH Gayle           720
...      ...          ...           ...
1526    2017     MM Patel             0
1527    2012  AC Blizzard             0
1528    2011     AB Dinda             0
1529    2017      AD Nath             0
1530    2008     L Balaji             0

[1531 rows x 3 columns]

In [38]:
#now we will drop all the players of each season except first occurred player of each season bcs we already sort it
#so we are going to use drop_duplicate(subset='season',keep='first') #1 keep only first #subset mean on which basis it will see duplicate
z=y.drop_duplicates('season').sort_values('season',ascending=False)
z#we also sorting it on the basis of season that we get a good dataframe

    season       batsman  batsman_runs
7     2017     DA Warner           641
0     2016       V Kohli           973
17    2015     DA Warner           562
6     2014    RV Uthappa           660
2     2013    MEK Hussey           733
3     2012      CH Gayle           733
11    2011      CH Gayle           608
9     2010  SR Tendulkar           618
14    2009     ML Hayden           572
10    2008      SE Marsh           616

In [41]:
#but if we only want to see the season and batsman_name
z[['season','batsman']] #z['season','batsman'] it will give error Because you're using a tuple as the key by writing it like this:
                        #it the same as z[('season', 'batsman')]
#and also if z will take only one argument that why we can only pass list if we want to fetch more than one column
#z[['season','batsman']] This tells Pandas: “Give me a new DataFrame containing only these two columns.”

    season       batsman
7     2017     DA Warner
0     2016       V Kohli
17    2015     DA Warner
6     2014    RV Uthappa
2     2013    MEK Hussey
3     2012      CH Gayle
11    2011      CH Gayle
9     2010  SR Tendulkar
14    2009     ML Hayden
10    2008      SE Marsh

In [42]:
#now all set